### ISSUE TITLE
0433BM15A0001 Pad spacing too wide

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/KiCad-Lib#14]
Not enough of the pad and solder paste reaches the underside of component, making placement difficult and reducing yield.
![padspacing](https://user-images.githubusercontent.com/10017555/27722681-e94e8638-5d1d-11e7-84dd-a1e809545556.png)

**Comment by Alenux55** [comment]
Using a [TDK component](https://www.digikey.ca/product-detail/en/tdk-corporation/DEA202450BT-7210A1/445-15654-2-ND/4321985) as reference; pads are closer.
![0433bm15a0001 update](https://user-images.githubusercontent.com/24886818/28702398-95eaa17a-7311-11e7-9827-0cfd6cd8001e.png)

**Comment by Alenux55** [comment]
Fixed in 2cb76bd
