### ISSUE TITLE
Add PC104 connectors

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/KiCad-Lib#2]
The smaller 16 bit connector should be enough

**Comment by TobiNakamura** [comment]
committed 6d26c2590282e700a34f9d8f6eba6b7e899c2796

**Comment by Alenux55** [comment]
Looks like the rows are reversed compared to the standard:
![pc104-8bit check](https://cloud.githubusercontent.com/assets/24886818/26661665/de008b88-4633-11e7-8db8-c7eb95dcd997.png)

Further, not a big deal, but can we change the pad diameter from **1.7272 mm** to **1.72 mm**? Numbers come from [this document](https://www.pcb-3d.com/knowledge-base/pth-dimensions/) using **Level A** and minimum hole diameter **1.02 mm**

**Comment by Alenux55** [comment]
Updated the connector in commit 63ce77d67ed47e621efd1c700e57982c8e002d00
![pc104-8bit_check_2](https://cloud.githubusercontent.com/assets/24886818/26711072/d599a238-4712-11e7-86b7-9cd5303c9403.png)
