### ISSUE TITLE
Add PC104 PTH

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/KiCad-Lib#3]
Add mechanical plated through holes that conforms with PC104

**Comment by TobiNakamura** [comment]
committed 48d65dc027d8708aceec9a7ec8f20d58987fb4a8

**Comment by Alenux55** [comment]
Hole diameter and pad diameter look good
![pc104-pth](https://cloud.githubusercontent.com/assets/24886818/26660773/f92f0380-462e-11e7-9fa6-065cdd2e1a13.png)
