### ISSUE TITLE
check SFH2430 footprint

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/KiCad-Lib#33]

**Comment by TobiNakamura** [comment]
Sch Lib: D_Photo (yes I know I'm not using the SFUSat library, its just a diode)
Footprint: SFUSat:SFH2430
Datasheet: https://www.mouser.com/ds/2/311/SFH%202430,%20Lead%20(Pb)%20Free%20Product%20-%20RoHS%20Compliant-335643.pdf

**Comment by JakubStacho** [comment]
This one looks fine to me.
