### ISSUE TITLE
Check DO-214AC-BI, SC-74, and SOT-23-3

### ISSUE THREAD

**Issue by Alenux55** [SFUSatClub/KiCad-Lib#35]
DO-214AC-BI: https://www.digikey.ca/products/en?keywords=SMAJ26CALFCT-ND
SC-74: https://www.digikey.ca/products/en?keywords=DCX124EK-FDICT-ND
SOT-23-3: https://www.digikey.ca/products/en?keywords=2N7002ET1GOSCT-ND

**Comment by JakubStacho** [comment]
All three of these footprints look good.
