### ISSUE TITLE
Check SMM4F5 footprint and symbol

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/KiCad-Lib#37]

**Comment by TobiNakamura** [comment]
Sch Lib: SMM4F5.0A-TR
Footprint: SFUSat:SMM4F
Datasheet: http://www.st.com/content/ccc/resource/technical/document/datasheet/5d/b3/40/b8/ac/6c/49/a2/CD00178940.pdf/files/CD00178940.pdf/jcr:content/translations/en.CD00178940.pdf

**Comment by JakubStacho** [comment]
Fixed issue. Changed K to C in the symbol.

25c188dd26142ba08cfe6034f8f194ebabf3b6d9
