### ISSUE TITLE
Add VDFN-8 package to SFUSat footprint lib

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/KiCad-Lib#40]
Footprint for this component:
https://media.digikey.com/pdf/Data%20Sheets/Texas%20Instruments%20PDFs/BQ29200,09.pdf
Take care to include the stencil geometry and the thermal pad vias.

**Comment by JakubStacho** [comment]
@TobiNakamura I've made the footprint and pushed my changes.
