### ISSUE TITLE
Check footprint Socket_Strip_Straight_2x05

### ISSUE THREAD

**Issue by Alenux55** [SFUSatClub/KiCad-Lib#9]
Used the following document: [https://drawings-pdf.s3.amazonaws.com/11091.pdf](https://drawings-pdf.s3.amazonaws.com/11091.pdf)

**Comment by TobiNakamura** [comment]
Checked layout for DO5-ST-BK. Also checked against figure 4 of CC debugger cable layout.
 (http://www.ti.com/lit/ug/swru197h/swru197h.pdf)
